const characters = [
  { character_name: "Edna Marie \"E\" Mode",
    date_of_birth: "Monday, 01/23/16 10:22am",
    views_count: 4,
    playlist_description: "Edna's \"Incredibles\" Hits",
    attachment_count: "04",
    image_url: "./assets/edna_mode_cartoon_character.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "Link to Learn More About Edna",
  },
  { character_name: "PLACEHOLDER",
    date_of_birth: "PLACEHOLDER",
    views_count: 4,
    playlist_description: "PLACEHOLDER",
    attachment_count: "04",
    image_url: "./assets/fish_cartoon.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "PLACEHOLDER",
  },
  { character_name: "PLACEHOLDER",
    date_of_birth: "PLACEHOLDER",
    views_count: 4,
    playlist_description: "PLACEHOLDER",
    attachment_count: "04",
    image_url: "./assets/all_disney_characters.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "PLACEHOLDER",
  },

  { character_name: "PLACEHOLDER",
    date_of_birth: "PLACEHOLDER",
    views_count: 4,
    playlist_description: "PLACEHOLDER",
    attachment_count: "04",
    image_url: "./assets/yoda_7203_700-700x340.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "PLACEHOLDER",
  },
  { character_name: "PLACEHOLDER",
    date_of_birth: "PLACEHOLDER",
    views_count: 4,
    playlist_description: "PLACEHOLDER",
    attachment_count: "04",
    image_url: "./assets/tomcruise_disney.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "PLACEHOLDER",
  },
  { character_name: "PLACEHOLDER",
    date_of_birth: "PLACEHOLDER",
    views_count: 4,
    playlist_description: "PLACEHOLDER",
    attachment_count: "04",
    image_url: "./assets/mickymouse_cast.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "PLACEHOLDER",
  },
  { character_name: "PLACEHOLDER",
    date_of_birth: "PLACEHOLDER",
    views_count: 4,
    playlist_description: "PLACEHOLDER",
    attachment_count: "04",
    image_url: "./assets/garfield_thecat.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "PLACEHOLDER",
  },
  { character_name: "PLACEHOLDER",
    date_of_birth: "PLACEHOLDER",
    views_count: 4,
    playlist_description: "PLACEHOLDER",
    attachment_count: "04",
    image_url: "./assets/charlie_brown_allcharacters.jpeg",
    info_url: "https://en.wikipedia.org/wiki/Edna_Mode",
    info_text: "PLACEHOLDER",
  },
]
